version: '3'
services:
  transfer:
    image: ptaylorexporo/link_hosted_zones:latest
    environment:
      - AWS_DEFAULT_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID= {{ AWS_SUB_ACCOUNT_ROOT_KEY_ID }}
      - AWS_SECRET_ACCESS_KEY= {{ AWS_SUB_ACCOUNT_ACCESS_KEY }}
      - AWS_ROOT_ACCESS_KEY_ID= {{ AWS_ROOT_KEY_ID }}
      - AWS_ROOT_SECRET_ACCESS_KEY= {{ AWS_ROOT_SECRET_ACCESS_KEY }}
      - RECORD_NAME=testing.test.io
      - ROOT_HOSTED_ZONE_NAME=test.io
